stack1: stack1.c 
	gcc -ggdb -Wmultichar -fno-stack-protector -o stack1 stack1.c

stack2: stack2.c 
	gcc -ggdb -fno-stack-protector -o stack2 stack2.c

stack3: stack3.c 
	gcc -ggdb -fno-stack-protector -o stack3 stack3.c

stack4: stack4.c 
	gcc -ggdb -fno-stack-protector -o stack4 stack4.c

stack5: stack5.c 
	gcc -ggdb -fno-stack-protector -o stack5 stack5.c
